export const CHANGE_ARTIST_SEARCHPHRASE = 'CHANGE_ARTIST_SEARCHPHRASE';
export const SEARCH_ARTISTS = 'SEARCH_ARTISTS';
export const ARTIST_RESULTS_READY = 'ARTIST_RESULTS_READY';

export const GET_ARTIST = 'GET_ARTIST';
export const ARTIST_READY = 'ARTIST_READY';

export const GET_ARTIST_ALBUMS = 'GET_ARTIST_ALBUMS';
export const ARTIST_ALBUMS_READY = 'ARTIST_ALBUMS_READY';

export const GET_ALBUM = 'GET_ALBUM';
export const ALBUM_READY = 'ALBUM_READY';